/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HelpRouteImport } from './routes/help'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVoiceRouteImport } from './routes/app.voice'
import { Route as AppTextRouteImport } from './routes/app.text'
import { Route as AppSubscriptionRouteImport } from './routes/app.subscription'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppResultsRouteImport } from './routes/app.results'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppLibraryRouteImport } from './routes/app.library'
import { Route as AppHomeRouteImport } from './routes/app.home'
import { Route as AppDiscoverRouteImport } from './routes/app.discover'
import { Route as AppProfileEditRouteImport } from './routes/app.profile.edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVoiceRoute = AppVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AppRoute,
} as any)
const AppTextRoute = AppTextRouteImport.update({
  id: '/text',
  path: '/text',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsRoute = AppResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileEditRoute = AppProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppProfileRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/home': typeof AppHomeRoute
  '/app/library': typeof AppLibraryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRouteWithChildren
  '/app/results': typeof AppResultsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/text': typeof AppTextRoute
  '/app/voice': typeof AppVoiceRoute
  '/app/profile/edit': typeof AppProfileEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/home': typeof AppHomeRoute
  '/app/library': typeof AppLibraryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRouteWithChildren
  '/app/results': typeof AppResultsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/text': typeof AppTextRoute
  '/app/voice': typeof AppVoiceRoute
  '/app/profile/edit': typeof AppProfileEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/home': typeof AppHomeRoute
  '/app/library': typeof AppLibraryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRouteWithChildren
  '/app/results': typeof AppResultsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/text': typeof AppTextRoute
  '/app/voice': typeof AppVoiceRoute
  '/app/profile/edit': typeof AppProfileEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/help'
    | '/privacy'
    | '/terms'
    | '/app/discover'
    | '/app/home'
    | '/app/library'
    | '/app/notifications'
    | '/app/profile'
    | '/app/results'
    | '/app/settings'
    | '/app/subscription'
    | '/app/text'
    | '/app/voice'
    | '/app/profile/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/help'
    | '/privacy'
    | '/terms'
    | '/app/discover'
    | '/app/home'
    | '/app/library'
    | '/app/notifications'
    | '/app/profile'
    | '/app/results'
    | '/app/settings'
    | '/app/subscription'
    | '/app/text'
    | '/app/voice'
    | '/app/profile/edit'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/help'
    | '/privacy'
    | '/terms'
    | '/app/discover'
    | '/app/home'
    | '/app/library'
    | '/app/notifications'
    | '/app/profile'
    | '/app/results'
    | '/app/settings'
    | '/app/subscription'
    | '/app/text'
    | '/app/voice'
    | '/app/profile/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  HelpRoute: typeof HelpRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/voice': {
      id: '/app/voice'
      path: '/voice'
      fullPath: '/app/voice'
      preLoaderRoute: typeof AppVoiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/text': {
      id: '/app/text'
      path: '/text'
      fullPath: '/app/text'
      preLoaderRoute: typeof AppTextRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscription': {
      id: '/app/subscription'
      path: '/subscription'
      fullPath: '/app/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/results': {
      id: '/app/results'
      path: '/results'
      fullPath: '/app/results'
      preLoaderRoute: typeof AppResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/discover': {
      id: '/app/discover'
      path: '/discover'
      fullPath: '/app/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile/edit': {
      id: '/app/profile/edit'
      path: '/edit'
      fullPath: '/app/profile/edit'
      preLoaderRoute: typeof AppProfileEditRouteImport
      parentRoute: typeof AppProfileRoute
    }
  }
}

interface AppProfileRouteChildren {
  AppProfileEditRoute: typeof AppProfileEditRoute
}

const AppProfileRouteChildren: AppProfileRouteChildren = {
  AppProfileEditRoute: AppProfileEditRoute,
}

const AppProfileRouteWithChildren = AppProfileRoute._addFileChildren(
  AppProfileRouteChildren,
)

interface AppRouteChildren {
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppHomeRoute: typeof AppHomeRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRouteWithChildren
  AppResultsRoute: typeof AppResultsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppTextRoute: typeof AppTextRoute
  AppVoiceRoute: typeof AppVoiceRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDiscoverRoute: AppDiscoverRoute,
  AppHomeRoute: AppHomeRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRouteWithChildren,
  AppResultsRoute: AppResultsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppTextRoute: AppTextRoute,
  AppVoiceRoute: AppVoiceRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  HelpRoute: HelpRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
