UI_STRINGS = {
    # Bottom navigation
    "nav.home": "Home",
    "nav.library": "Library",
    "nav.discover": "Discover",
    "nav.profile": "Profile",
    # Home screen
    "home.greeting.morning": "Good morning",
    "home.greeting.afternoon": "Good afternoon",
    "home.greeting.evening": "Good evening",
    "home.tapToIdentify": "Tap to identify a verse",
    "home.recentSearches": "Recent searches",
    "home.verseOfDay": "Verse of the day",
    # Common actions
    "action.save": "Save",
    "action.saved": "Saved",
    "action.share": "Share",
    "action.copy": "Copy",
    "action.tryAgain": "Try again",
    "action.cancel": "Cancel",
    "action.confirm": "Confirm",
    "action.done": "Done",
    "action.back": "Back",
    # Results screen
    "action.listen": "Listen",
    "action.stop": "Stop",
    "action.shareText": "Share text",
    "action.copied": "Copied",
    "action.shareImage": "Share image",
    "action.creating": "Creating…",
    "action.backToLibrary": "Back to Library",
    # Voice screen
    "voice.listening": "Listening…",
    "voice.identifying": "Identifying verse…",
    "voice.speakPrompt": "Speak any verse you remember",
    "voice.typeInstead": "Type instead",
    # Library screen
    "library.title": "Library",
    "library.subtitle": "Your saved verses & history",
    "library.tab.saved": "Saved",
    "library.tab.collections": "Collections",
    "library.tab.history": "History",
    "library.clearAll": "Clear all",
    "library.clearAllConfirm": "Clear all history?",
    "library.emptySaved": "No saved verses yet. Tap save on any result.",
    "library.emptyHistory": "Your search history will appear here.",
    "library.noMatchFound": "No match found",
    # Screen titles
    "notifications.title": "Notifications",
    "profile.title": "Profile",
    "settings.title": "Settings",
    # Settings group headings
    "settings.group.preferences": "Preferences",
    "settings.group.notifications": "Notification preferences",
    "settings.group.bibleVersion": "Bible version",
    "settings.group.interfaceLanguage": "Interface language",
    "settings.group.appearance": "Appearance",
    "settings.group.account": "Account",
}